#!/usr/bin/env python3

"""Guide and safely advance AI Website Factory project stages."""

from datetime import datetime, timezone
from pathlib import Path
import os
import stat
import subprocess
import sys
import tempfile

from factory_stages import STAGES, NEXT_STAGE, ALIASES


FACTORY_ROOT = Path(__file__).resolve().parent.parent
HANDOFF_MARKER = "<!-- Generated by ./factory handoff. Manual edits may be replaced. -->"

HANDOFF_SEQUENCE = (
    "Architecture", "Design", "Development", "QA", "SEO", "Security",
    "Performance", "Accessibility", "Final Review", "Ready for Human Approval",
    "Approved", "Deployment Ready",
)

HANDOFF_ARTIFACTS = (
    ("Project brief", "PROJECT-BRIEF.md", "Architecture"),
    ("Project status", "PROJECT-STATUS.md", "Architecture"),
    ("Approved architecture", "architecture/ARCHITECTURE.md", "Design"),
    ("UI/UX specification", "design/UI-UX-SPEC.md", "Development"),
    ("Development documentation", "documentation/DEVELOPMENT.md", "QA"),
    ("Implementation", "src", "QA"),
    ("QA report", "reports/QA-REPORT.md", "SEO"),
    ("SEO report", "reports/SEO-REPORT.md", "Security"),
    ("Security report", "reports/SECURITY-REPORT.md", "Performance"),
    ("Performance report", "reports/PERFORMANCE-REPORT.md", "Accessibility"),
    ("Accessibility report", "reports/ACCESSIBILITY-REPORT.md", "Final Review"),
    ("Launch-readiness report", "reports/LAUNCH-READINESS.md", "Ready for Human Approval"),
    ("Deployment plan", "documentation/DEPLOYMENT.md", "Ready for Human Approval"),
)


def read_sections(status_file):
    text = status_file.read_text(encoding="utf-8")
    sections = {}
    current_heading = None

    for line in text.splitlines():
        if line.startswith("## "):
            current_heading = line[3:].strip()
            sections[current_heading] = []
        elif current_heading is not None:
            sections[current_heading].append(line)

    return text, {
        heading: "\n".join(lines).strip()
        for heading, lines in sections.items()
    }


def current_stage(sections):
    value = sections.get("Current Stage", "").strip()
    first_line = next((line.strip() for line in value.splitlines() if line.strip()), "")
    return ALIASES.get(first_line, first_line)


def has_blockers(sections):
    blockers = sections.get("Blockers", "").strip()
    if not blockers:
        return False
    first_line = blockers.splitlines()[0].strip().lower()
    return not first_line.startswith(("none", "no blocker"))


def run_tool(command):
    return subprocess.run(command, capture_output=True, text=True, check=False)


def gate_errors(project_name, project_directory, stage, sections, allow_human_approval=False):
    errors = []
    if has_blockers(sections):
        errors.append("PROJECT-STATUS.md contains active blockers")

    if stage == "Approved":
        validator = FACTORY_ROOT / "tools" / "validate-release.py"
        validator_command = [sys.executable, str(validator), project_name, str(project_directory)]
        validator_error = f"release validation is failing; run './factory validate-release {project_name}'"
    else:
        validator = FACTORY_ROOT / "tools" / "validate-stage.py"
        validator_command = [
            sys.executable,
            str(validator),
            project_name,
            str(project_directory),
            stage,
        ]
        validator_error = f"stage validation is failing; run './factory validate-stage {project_name}'"

    if not validator.is_file():
        errors.append(f"workflow validator is missing at {validator.relative_to(FACTORY_ROOT)}")
    else:
        result = run_tool(validator_command)
        if result.returncode != 0:
            errors.append(validator_error)

    if stage == "Ready for Human Approval" and not allow_human_approval:
        errors.append("generic advancement cannot grant human approval")
    elif stage == "Deployment Ready":
        errors.append("generic advancement cannot deploy a production project")
    elif stage == "Blocked":
        errors.append("resolve the documented blocker and set an explicit recovery state")

    return errors


def replace_section(text, heading, new_body):
    lines = text.splitlines()
    heading_line = f"## {heading}"

    try:
        heading_index = lines.index(heading_line)
    except ValueError as error:
        raise ValueError(f"PROJECT-STATUS.md is missing the '{heading}' section") from error

    end_index = len(lines)
    for index in range(heading_index + 1, len(lines)):
        if lines[index].startswith("## "):
            end_index = index
            break

    replacement = [heading_line, "", *new_body.splitlines(), ""]
    return "\n".join(lines[:heading_index] + replacement + lines[end_index:]).rstrip() + "\n"


def completed_stages_body(existing, completed_stage):
    normalized = existing.strip()
    if normalized.lower() in ("", "none", "none identified."):
        lines = []
    else:
        lines = normalized.splitlines()

    entry = f"- {completed_stage}"
    if entry not in lines:
        lines.append(entry)
    return "\n".join(lines)


def write_status(status_file, text):
    original_mode = stat.S_IMODE(status_file.stat().st_mode)
    temporary_path = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=status_file.parent,
            prefix=".PROJECT-STATUS.",
            suffix=".tmp",
            delete=False,
        ) as temporary_file:
            temporary_file.write(text)
            temporary_path = Path(temporary_file.name)
        os.chmod(temporary_path, original_mode)
        os.replace(temporary_path, status_file)
    finally:
        if temporary_path is not None and temporary_path.exists():
            temporary_path.unlink()


def status_section(sections, heading, default="Not documented."):
    value = sections.get(heading, "").strip()
    return value or default


def project_assumptions(project_directory):
    architecture_file = project_directory / "architecture" / "ARCHITECTURE.md"
    if not architecture_file.is_file():
        return "No architecture assumptions are documented yet."

    try:
        _, sections = read_sections(architecture_file)
    except (OSError, UnicodeDecodeError):
        return "Architecture assumptions could not be read; review architecture/ARCHITECTURE.md manually."
    return status_section(sections, "Assumptions", "No architecture assumptions are documented yet.")


def relevant_files(project_directory, destination):
    destination_index = HANDOFF_SEQUENCE.index(destination)
    lines = []
    for label, relative_path, first_destination in HANDOFF_ARTIFACTS:
        if HANDOFF_SEQUENCE.index(first_destination) > destination_index:
            continue
        state = "" if (project_directory / relative_path).exists() else " — not present; confirm before starting"
        lines.append(f"- [{label}]({relative_path}){state}")
    return "\n".join(lines) or "- [Project status](PROJECT-STATUS.md)"


def render_handoff(project_name, project_directory, sections, stage, destination):
    source = STAGES[stage]
    target = STAGES[destination]
    source_agent = source["agent"]
    target_agent = target["agent"]

    lines = [
        HANDOFF_MARKER,
        "",
        f"# Agent Handoff — {project_name}",
        "",
        "## Transition",
        "",
        f"- **Source stage:** {stage}",
        f"- **Source owner:** {source['owner']}",
        f"- **Destination stage:** {destination}",
        f"- **Destination owner:** {target['owner']}",
        "- **Workflow gate:** Ready",
    ]
    if source_agent:
        lines.append(f"- **Source agent instructions:** [../../{source_agent}](../../{source_agent})")
    if target_agent:
        lines.append(f"- **Destination agent instructions:** [../../{target_agent}](../../{target_agent})")

    lines.extend(
        [
            "",
            "## Assignment",
            "",
            target["action"],
            "",
            "## Required Output",
            "",
            f"`{target['output']}`",
            "",
            "## Relevant Files",
            "",
            relevant_files(project_directory, destination),
            "",
            "## Requirements",
            "",
            "- Treat `PROJECT-BRIEF.md` as the source of truth for project requirements.",
            "- Follow approved upstream deliverables and record any necessary deviations.",
            "- Keep work limited to the destination stage and its required output.",
            "- Do not deploy to production without explicit human approval.",
            "",
            "## Assumptions",
            "",
            project_assumptions(project_directory),
            "",
            "## Known Issues",
            "",
            status_section(sections, "Known Issues"),
            "",
            "## Blockers",
            "",
            status_section(sections, "Blockers", "None identified."),
            "",
            "## Human Decisions Required",
            "",
            status_section(sections, "Human Decisions Required"),
            "",
            "## Definition of Done",
            "",
            f"- The {destination} assignment is complete and matches the project brief.",
            f"- `{target['output']}` contains substantive, reviewable work.",
            "- Assumptions, limitations, blockers, and known issues are documented.",
            "- Existing approved work is preserved unless a documented requirement calls for a change.",
            f"- `./factory validate-stage {project_name}` passes after the project enters {destination}.",
            "",
            "## Workflow Commands",
            "",
            f"1. Review this handoff, then run `./factory advance {project_name}`.",
            f"2. Complete the assignment and run `./factory validate-stage {project_name}`.",
            f"3. When the stage is ready, run `./factory handoff {project_name}` for the following agent.",
            "",
        ]
    )
    return "\n".join(lines)


def write_handoff(handoff_file, text):
    original_mode = 0o644
    if handoff_file.exists():
        try:
            existing = handoff_file.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError) as error:
            raise ValueError(f"could not read existing HANDOFF.md: {error}") from error
        if not existing.startswith(HANDOFF_MARKER):
            raise ValueError("HANDOFF.md was not generated by the factory; refusing to overwrite it")
        original_mode = stat.S_IMODE(handoff_file.stat().st_mode)

    temporary_path = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=handoff_file.parent,
            prefix=".HANDOFF.",
            suffix=".tmp",
            delete=False,
        ) as temporary_file:
            temporary_file.write(text)
            temporary_path = Path(temporary_file.name)
        os.chmod(temporary_path, original_mode)
        os.replace(temporary_path, handoff_file)
    finally:
        if temporary_path is not None and temporary_path.exists():
            temporary_path.unlink()


def load_project(project_name, project_directory):
    status_file = project_directory / "PROJECT-STATUS.md"
    if not status_file.is_file():
        raise ValueError(f"project '{project_name}' has no PROJECT-STATUS.md file")

    try:
        text, sections = read_sections(status_file)
    except (OSError, UnicodeDecodeError) as error:
        raise ValueError(f"could not read {status_file}: {error}") from error

    stage = current_stage(sections)
    if stage not in STAGES:
        raise ValueError(f"unrecognized current stage '{stage or 'empty'}'")
    return status_file, text, sections, stage


def show_next(project_name, project_directory):
    _, _, sections, stage = load_project(project_name, project_directory)
    details = STAGES[stage]

    print(f"Project: {project_name}")
    print(f"Current stage: {stage}")
    print(f"Current owner: {details['owner']}")

    if stage == "Deployed":
        print("Workflow status: COMPLETE")
        print("Next stage: None")
        return 0
    if stage == "Blocked":
        print("Workflow status: BLOCKED")
        print(f"Next action: {details['action']}")
        return 1

    destination = NEXT_STAGE.get(stage)
    if destination is None:
        raise ValueError(f"no transition is configured from '{stage}'")

    destination_details = STAGES[destination]
    errors = gate_errors(project_name, project_directory, stage, sections)

    print(f"Next stage: {destination}")
    print(f"Next owner: {destination_details['owner']}")
    if destination_details["agent"]:
        print(f"Agent instructions: {destination_details['agent']}")
    print(f"Required output: {details['output']}")

    if errors:
        print("Gate: BLOCKED")
        for error in errors:
            print(f"  - {error}")
        return 1

    print("Gate: READY")
    print(f"Advance with: ./factory advance {project_name}")
    return 0


def create_handoff(project_name, project_directory):
    _, _, sections, stage = load_project(project_name, project_directory)

    if stage == "Deployed":
        print(f"NOT CREATED: project '{project_name}' is already deployed and has no next-stage handoff.", file=sys.stderr)
        return 1
    if stage == "Blocked":
        print(f"NOT CREATED: project '{project_name}' is blocked; resolve its blockers before handoff.", file=sys.stderr)
        return 1

    destination = NEXT_STAGE.get(stage)
    if destination is None:
        print(f"NOT CREATED: no handoff destination is configured from '{stage}'.", file=sys.stderr)
        return 1

    errors = gate_errors(project_name, project_directory, stage, sections)
    if errors:
        print(f"NOT CREATED: {project_name} is not ready for handoff from {stage}.", file=sys.stderr)
        for error in errors:
            print(f"  - {error}", file=sys.stderr)
        return 1

    target_agent = STAGES[destination]["agent"]
    if target_agent and not (FACTORY_ROOT / target_agent).is_file():
        print(f"NOT CREATED: destination agent instructions are missing at {target_agent}.", file=sys.stderr)
        return 1

    handoff_file = project_directory / "HANDOFF.md"
    handoff_text = render_handoff(project_name, project_directory, sections, stage, destination)
    existed = handoff_file.exists()
    try:
        write_handoff(handoff_file, handoff_text)
    except (OSError, ValueError) as error:
        print(f"NOT CREATED: could not write HANDOFF.md ({error}).", file=sys.stderr)
        return 1

    action = "Refreshed" if existed else "Created"
    print(f"{action} handoff: projects/{project_name}/HANDOFF.md")
    print(f"Transition: {stage} -> {destination}")
    print(f"Destination owner: {STAGES[destination]['owner']}")
    print("Project status was not changed.")
    return 0


def approve(project_name, project_directory, confirmation):
    if confirmation != "APPROVED":
        print(
            f"NOT APPROVED: confirmation must be exactly 'APPROVED'. "
            f"Run './factory approve {project_name} APPROVED' after reviewing the launch evidence.",
            file=sys.stderr,
        )
        return 1

    status_file, text, sections, stage = load_project(project_name, project_directory)
    if stage != "Ready for Human Approval":
        print(
            f"NOT APPROVED: project '{project_name}' is in {stage}, not Ready for Human Approval.",
            file=sys.stderr,
        )
        return 1

    errors = gate_errors(
        project_name,
        project_directory,
        stage,
        sections,
        allow_human_approval=True,
    )
    if errors:
        print(f"NOT APPROVED: {project_name} did not pass the human approval gate.", file=sys.stderr)
        for error in errors:
            print(f"  - {error}", file=sys.stderr)
        return 1

    recorded_at = datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    previous_decision_context = status_section(
        sections,
        "Human Decisions Required",
        "Explicit human approval was required before release preparation.",
    )
    approval_record = "\n".join(
        (
            "No production approval decision is pending.",
            "",
            "Approval record:",
            "- **Decision:** APPROVED",
            f"- **Recorded at:** {recorded_at}",
            f"- **Recorded through:** `./factory approve {project_name} APPROVED`",
            "- **Evidence:** `reports/LAUNCH-READINESS.md`",
            "- **Scope:** Authorizes release preparation only; no deployment was performed.",
            "",
            "Decision context presented before approval:",
            previous_decision_context,
        )
    )
    target = STAGES["Approved"]
    completed = completed_stages_body(sections.get("Completed Stages", ""), stage)
    next_action = (
        f"{target['action']} Required output: {target['output']}. "
        f"Run './factory validate-stage {project_name}' when the deployment plan is complete. "
        "A separate explicit instruction is still required for production deployment."
    )

    try:
        text = replace_section(text, "Current Stage", "Approved")
        text = replace_section(text, "Current Owner", target["owner"])
        text = replace_section(text, "Completed Stages", completed)
        text = replace_section(text, "Active Work", target["action"])
        text = replace_section(text, "Human Decisions Required", approval_record)
        text = replace_section(text, "Next Action", next_action)
        write_status(status_file, text)
    except (OSError, ValueError) as error:
        print(f"NOT APPROVED: could not update PROJECT-STATUS.md ({error}).", file=sys.stderr)
        return 1

    print(f"Human approval recorded: {project_name}")
    print("Transition: Ready for Human Approval -> Approved")
    print(f"Recorded at: {recorded_at}")
    print("No deployment was performed.")
    return 0


def advance(project_name, project_directory):
    status_file, text, sections, stage = load_project(project_name, project_directory)
    if stage == "Deployed":
        print(f"Project '{project_name}' is already deployed; no workflow transition was made.", file=sys.stderr)
        return 1

    destination = NEXT_STAGE.get(stage)
    if destination is None:
        print(f"Project '{project_name}' cannot advance from '{stage}'.", file=sys.stderr)
        return 1

    errors = gate_errors(project_name, project_directory, stage, sections)
    if errors:
        print(f"NOT ADVANCED: {project_name} remains in {stage}.", file=sys.stderr)
        for error in errors:
            print(f"  - {error}", file=sys.stderr)
        return 1

    destination_details = STAGES[destination]
    completed = completed_stages_body(sections.get("Completed Stages", ""), stage)
    next_action = (
        f"{destination_details['action']} Required output: {destination_details['output']}. "
        f"When complete, run './factory next {project_name}'."
    )

    try:
        text = replace_section(text, "Current Stage", destination)
        text = replace_section(text, "Current Owner", destination_details["owner"])
        text = replace_section(text, "Completed Stages", completed)
        text = replace_section(text, "Active Work", destination_details["action"])
        text = replace_section(text, "Next Action", next_action)
        if destination == "Ready for Human Approval":
            text = replace_section(
                text,
                "Human Decisions Required",
                "Explicit human approval is required before any production deployment.",
            )
        write_status(status_file, text)
    except (OSError, ValueError) as error:
        print(f"Error: could not update PROJECT-STATUS.md ({error}).", file=sys.stderr)
        return 1

    print(f"Advanced {project_name}: {stage} -> {destination}")
    print(f"Owner: {destination_details['owner']}")
    print(f"Next action: {destination_details['action']}")
    print(f"Required output: {destination_details['output']}")
    return 0


def main():
    command = sys.argv[1] if len(sys.argv) > 1 else ""
    standard_command = command in ("next", "handoff", "advance") and len(sys.argv) == 4
    approval_command = command == "approve" and len(sys.argv) == 5
    if not standard_command and not approval_command:
        print(
            "Usage: workflow-controller.py <next|handoff|advance> <project-name> <project-directory>\n"
            "       workflow-controller.py approve <project-name> <project-directory> APPROVED",
            file=sys.stderr,
        )
        return 2

    project_name = sys.argv[2]
    project_directory = Path(sys.argv[3]).resolve()

    try:
        if command == "next":
            return show_next(project_name, project_directory)
        if command == "handoff":
            return create_handoff(project_name, project_directory)
        if command == "approve":
            return approve(project_name, project_directory, sys.argv[4])
        return advance(project_name, project_directory)
    except ValueError as error:
        print(f"Error: {error}.", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
